version: '3.8'

services:
  web:
    container_name: runners-list-web-prod
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped